# Generated by Django 4.1.5 on 2023-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('datahora_adicionado', models.DateTimeField(auto_now_add=True)),
                ('datahora_modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
