# Generated by Django 4.1.5 on 2023-01-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='datahora_adicionado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='datahora_modificado',
        ),
    ]
